import api from './api';
export const grantPermission = (data) => api.post('/permission/grant', data);
export const grantStaffPermission = (data) => api.post('/permission/grant-staff', data);
export const getActivePermissions = () => api.get('/permission/active');
export const grantEmergencyPermission = (data) => api.post('/permission/emergency', data);
export const getEmergencyHistory = (params) => api.get('/permission/emergency/history', { params });
export const getAllPermissions = (params) => api.get('/permission/all', { params });
export const getPendingPermissions = () => api.get('/permission/pending-staff');
export const approveStaffPermission = (id) => api.post(`/permission/approve-staff/${id}`);
export const rejectStaffPermission = (id) => api.post(`/permission/reject-staff/${id}`);
export const recordStaffPermissionOut = (data) => api.post('/permission/staff-out', data);
export const getMyPermissions = () => api.get('/permission/student/my-permissions');
